trigger:
  - none

jobs:
  - job: WebApp
    displayName: Build Web App
    pool:
      vmImage: ubuntu-latest
    variables:
      buildConfiguration: Release
    steps:  # <-- This must be inside the job
      - task: DotNetCoreCLI@2
        displayName: Nuget Restore
        inputs:
          command: restore
          projects: '**/WebApp.csproj'
          feedsToUse: select

      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          command: build
          projects: '**/WebApp.csproj'
          arguments: '--configuration $(buildConfiguration)'

      - task: DotNetCoreCLI@2
        displayName: Run Unit Tests
        condition: false
        inputs:
          command: test
          projects: '**/*UnitTest*.csproj'
          arguments: '--configuration $(buildConfiguration)'
          testRunTitle: Run Unit Tests

      - task: DotNetCoreCLI@2
        displayName: Publish
        inputs:
          command: publish
          publishWebProjects: true
          arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)'

      - task: PublishBuildArtifacts@1
        displayName: Publish Artifact
        inputs:
          PathtoPublish: $(Build.ArtifactStagingDirectory)
          ArtifactName: drop
          publishLocation: Container
